/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nchash_view_CppHook */

#ifndef _Included_com_nchash_view_CppHook
#define _Included_com_nchash_view_CppHook
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nchash_view_CppHook
 * Method:    printMsg
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_nchash_view_CppHook_printMsg
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_nchash_view_CppHook
 * Method:    client_caller
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nchash_view_CppHook_client_1caller
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
